SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE dbo.AttLog (
ID INT NOT NULL IDENTITY, 
PIN VARCHAR(50), 
AttTime DATETIME, 
Status VARCHAR(10), 
Verify VARCHAR(10), 
WorkCode VARCHAR(50), 
Reserved1 VARCHAR(50), 
Reserved2 VARCHAR(50), 
DeviceID VARCHAR(50), 
MaskFlag INT, 
Temperature VARCHAR(50), 
PRIMARY KEY (ID), 
CONSTRAINT ATTLOG_UNIQUE UNIQUE (PIN, PIN, AttTime, AttTime));

CREATE TABLE dbo.Device (
ID INT NOT NULL IDENTITY, 
DevSN VARCHAR(50), 
DevName VARCHAR(50), 
ATTLOGStamp VARCHAR(50), 
OPERLOGStamp VARCHAR(50), 
ATTPHOTOStamp VARCHAR(50), 
ErrorDelay VARCHAR(50), 
Delay VARCHAR(50), 
TransFlag VARCHAR(100), 
Realtime VARCHAR(1), 
TransInterval VARCHAR(10), 
TransTimes VARCHAR(60), 
Encrypt VARCHAR(1), 
LastRequestTime DATETIME, 
DevIP VARCHAR(50), 
DevMac VARCHAR(50), 
DevFPVersion VARCHAR(50), 
DevFirmwareVersion VARCHAR(50), 
UserCount INT, 
AttCount INT, 
FpCount INT, 
TimeZone VARCHAR(50), 
Timeout INT, 
SyncTime INT, 
VendorName VARCHAR(50), 
IRTempDetectionFunOn VARCHAR(1), 
MaskDetectionFunOn VARCHAR(1), 
UserPicURLFunOn VARCHAR(1) DEFAULT '0', 
MultiBioDataSupport VARCHAR(50), 
MultiBioPhotoSupport VARCHAR(50), 
MultiBioVersion VARCHAR(100), 
MultiBioCount VARCHAR(100), 
MaxMultiBioDataCount VARCHAR(100), 
MaxMultiBioPhotoCount VARCHAR(100), 
PRIMARY KEY (ID), 
CONSTRAINT DEVSN_UNIQUE UNIQUE (DevSN, DevSN));

CREATE TABLE dbo.DeviceCmds (
ID INT NOT NULL IDENTITY, 
DevSN VARCHAR(50), 
Content TEXT, 
CommitTime DATETIME, 
TransTime DATETIME, 
ResponseTime DATETIME, 
ReturnValue VARCHAR(8000), 
PRIMARY KEY (ID));

CREATE TABLE dbo.ErrorLog (
ID INT NOT NULL IDENTITY, 
ErrCode VARCHAR(100) NOT NULL, 
ErrMsg TEXT, 
DataOrigin VARCHAR(50), 
CmdId VARCHAR(100), 
Additional TEXT, 
DeviceID VARCHAR(50), 
PRIMARY KEY (ID));

CREATE TABLE dbo.OpLog (
ID INT NOT NULL IDENTITY, 
Operator VARCHAR(50), 
OpTime DATETIME, 
OpType VARCHAR(10), 
User VARCHAR(50), 
Obj1 VARCHAR(50), 
Obj2 VARCHAR(50), 
Obj3 VARCHAR(50), 
Obj4 VARCHAR(50), 
DeviceID VARCHAR(50), 
PRIMARY KEY (ID));

CREATE TABLE dbo.SMS (
ID INT NOT NULL IDENTITY, 
SMSId INT, 
Type INT, 
ValidTime INT, 
BeginTime DATETIME, 
UserID VARCHAR(50), 
Content VARCHAR(320), 
PRIMARY KEY (ID));

CREATE TABLE dbo.sqlite_sequence (
name VARCHAR(20) NOT NULL, 
seq INT NOT NULL);

CREATE TABLE dbo.TmpBioData (
ID INT NOT NULL IDENTITY, 
Pin VARCHAR(50), 
No VARCHAR(2) DEFAULT '0', 
Index VARCHAR(2), 
Valid VARCHAR(1) DEFAULT '1', 
Duress VARCHAR(1) DEFAULT '0', 
Type VARCHAR(2), 
MajorVer VARCHAR(20), 
MinorVer VARCHAR(20), 
Format VARCHAR(20), 
Tmp TEXT, 
PRIMARY KEY (ID));

CREATE TABLE dbo.TmpBioPhoto (
ID INT NOT NULL IDENTITY, 
Pin VARCHAR(50), 
FileName VARCHAR(100), 
Type VARCHAR(20), 
Size INT DEFAULT 0, 
Content TEXT, 
PRIMARY KEY (ID));

CREATE TABLE dbo.TmpFace (
ID INT NOT NULL IDENTITY, 
Pin VARCHAR(50), 
Fid VARCHAR(2) DEFAULT '0', 
Size INT DEFAULT 0, 
Valid VARCHAR(1) DEFAULT '1', 
Tmp TEXT, 
Ver VARCHAR(20), 
PRIMARY KEY (ID));

CREATE TABLE dbo.TmpFP (
ID INT NOT NULL IDENTITY, 
Pin VARCHAR(50), 
Fid VARCHAR(2) DEFAULT '0', 
Size INT DEFAULT 0, 
Valid VARCHAR(1) DEFAULT '1', 
Tmp VARCHAR(2000), 
MajorVer VARCHAR(20), 
MinorVer VARCHAR(20), 
Duress VARCHAR(1) DEFAULT '0', 
PRIMARY KEY (ID));

CREATE TABLE dbo.TmpFvein (
ID INT NOT NULL IDENTITY, 
Pin VARCHAR(50), 
Fid VARCHAR(2) DEFAULT '0', 
Index VARCHAR(2) DEFAULT '0', 
Size INT DEFAULT 0, 
Valid VARCHAR(1) DEFAULT '1', 
Tmp TEXT, 
Ver VARCHAR(20), 
Duress VARCHAR(1) DEFAULT '0', 
PRIMARY KEY (ID));

CREATE TABLE dbo.TmpUserPic (
ID INT NOT NULL IDENTITY, 
Pin VARCHAR(50), 
FileName VARCHAR(100), 
Size INT DEFAULT 0, 
Content TEXT, 
PRIMARY KEY (ID));

CREATE TABLE dbo.UserInfo (
ID INT NOT NULL IDENTITY, 
DevSN VARCHAR(50), 
PIN VARCHAR(50), 
UserName VARCHAR(100), 
Passwd VARCHAR(20), 
IDCard VARCHAR(50), 
Grp VARCHAR(50), 
TZ VARCHAR(50), 
Pri VARCHAR(2), 
PRIMARY KEY (ID), 
CONSTRAINT PIN_UNIQUE UNIQUE (PIN, PIN));

CREATE TABLE dbo.Workcode (
ID INT NOT NULL IDENTITY, 
workcode VARCHAR(4) NOT NULL, 
workname VARCHAR(50), 
PRIMARY KEY (ID));
